% Function name....: FiltSig
% Date.............: July 03, 2015
% Author...........: Adriano O. Andrade, PhD (aoandrade@feelt.ufu.br)
% Description......:
%                    applies a band-pass filter (1 to Fs/2 Hz) to the input time series
%                    y. 
% Parameters.......: 
%                    y -> input time-series
%                    Fs    -> sampling frequency (Hz)
% Return...........:
%                    yfilt -> filtered signal
% Remarks..........:

function [yfilt] = FiltSig(y,Fs)
    % MATLAB Code
    % Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
    % Generated on: 29-Jun-2015 23:24:24

    % Butterworth Highpass filter designed using FDESIGN.HIGHPASS.

    % All frequency values are in Hz.

    Fstop = 0.1;         % Stopband Frequency
    Fpass = 1;           % Passband Frequency
    Astop = 80;          % Stopband Attenuation (dB)
    Apass = 1;           % Passband Ripple (dB)
    match = 'passband';  % Band to match exactly

    % Construct an FDESIGN object and call its BUTTER method.
    h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs/2);
    Hd = design(h, 'butter', 'MatchExactly', match);
    %freqz(Hd,1000,'whole', Fs); visualize the filter response

    yfilt = filtfilt(Hd.sosMatrix, Hd.ScaleValues, y) ;

end