% Function name....: PassBandFiltButter
% Date.............: May 17, 2015
% Author...........: Adriano O. Andrade, PhD (aoandrade@feelt.ufu.br)
% Description......:
%                    applies a band -pass filter to the input time series y
% Parameters.......: 
%                    y -> input time-series
%                    LcutoffFreq -> lower cutoff frequency (Hz)
%                    UcutoffFreq -> upper cutoof frequency (Hz)
%                    order       -> filter order
%                    sampFreq    -> sampling frequency (Hz)
% Return...........:
%                    yfilt -> filtered signal
% Remarks..........:


function [yfilt] = FiltSig(y,LcutoffFreq,UcutoffFreq,order,sampFreq)

  % Wn = [LcutoffFreq UcutoffFreq]/(sampFreq/2);
  % [b,a] = butter(order,Wn); %filter design
  % yfilt = filtfilt(b,a,y); %zero-phase digital filtering (zero-phase distortion)
  
  Hd = FilterTeste; 
  yfilt = filtfilt(Hd.sosMatrix, Hd.ScaleValues, y) ;
    
end


function Hd = FilterTeste
%FILTERTESTE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 29-Jun-2015 23:24:24

% Butterworth Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 50;  % Sampling Frequency

Fstop = 0.1;         % Stopband Frequency
Fpass = 1;           % Passband Frequency
Astop = 80;          % Stopband Attenuation (dB)
Apass = 1;           % Passband Ripple (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

end